### ISSUE TITLE
Failed to install desktop menu item?

### ISSUE THREAD

**Issue by Wowfunhappy** [kujeger/flatpak-gog#1]
I only own two GoG games that support Linux, and neither are on the existing compatibility list, but I don't think this should be a game-specific issue?

When I try to build the generated json file of either Firewatch or Finding Paradise, I get the following error:
```
Installing
Metadata
gog_com-Firewatch_1.desktop: 100% (total progress: 99%)
NOTICE: Failed to install desktop menu item
[hit enter]
Incomplete installation. We will revert any changes we made.
```
Why would the desktop menu file, of all things, be failing? Please let me know if I can provide more information.

Thank you!

**Comment by kujeger** [comment]
Hi!
A small change in the sed command that edits the desktop file was just pushed. It's possible that fixes it for you; could you try again with the most recent master?

**Comment by kujeger** [comment]
With #7 this should be fixed, please reopen if that's not the case.
