### ISSUE TITLE
OpenSSL 1.0.x EOL

### ISSUE THREAD

**Issue by V02460** [kujeger/flatpak-gog#17]
The freedesktop runtime does no longer ship with OpenSSL 1.0.x, which is a good thing as this version is [no longer maintained](https://en.wikipedia.org/wiki/OpenSSL#Major_version_releases) and thus a security risk. Unfortunately, some games on GOG (e.g. [Undertale](https://www.gog.com/game/undertale)) still require this old versions to run.

**Comment by kujeger** [comment]
I've commited an initial module and override that works for 64bit at least, in 325c686 . The openssl-1.0.x build system is a bit weird.

**Comment by kujeger** [comment]
Ended up with two modules, one for 64bit and one for 32bit. It's not ideal, but it works: 00a4bb2
