### ISSUE TITLE
Make it a C-compatible library

### ISSUE THREAD

**Issue by Kekun** [kujeger/flatpak-gog#22]
That'd be cool to make it an C-compatible and installable library, that would allow any app to use it to bundle and install GOG games for their users. You could then even offer a cool little GUI app on Flathub for it to be more user-friendly.

I am suggesting this with GNOME Games in mind: I'd like it to be able to install GOG games by flatpaking them, but we would need feedbak e.g. on how long the installation is taling, etc, and the current script doesn't allow us to do that.

**Comment by V02460** [comment]
You are mentioning some different aspects, so here’s a try to address them:

The current script is C-compatible in a weak sense: You can call it and read its output. It’s also (kind-of) installable: Put it into e.g. `/usr/local/bin`. It could be made better by looking for its auxiliary files in proper locations and maybe have more machine-readable output.

This Python script is not a library, but it has such a simple interface that it is probably not needed right now. Publishing it on PyPI and optionally making it function as a libary, too, might be worth a thought.

GNOME Games does already support Flatpaks – and as far as I can see it’s not their business to install them. Installing can be done by e.g. GNOME Software and it’s doing it just fine for me right now, including progress bars^^ This is under the premise of an existing Flatpak repo filled with already-built GOG games.

For the scenario of downloading, building, installing and running a GOG game on demand with a click of a button, this script only does the preparation of the build using the downloaded installer, which is very fast. flatpak-builder, which is used for building does not give any feedback on how long its build is going to take and architecturally that should only be possible on a module level, which is not very helpful. The GOG installer run during the build gives feedback, which could be used with some stdout scraping to estimate the build-progress.

Maybe you can elaborate a bit more what you want to archive and I can help you with a better answer.
