### ISSUE TITLE
Terraria: Mouse not working.

### ISSUE THREAD

**Issue by Muvkina** [kujeger/flatpak-gog#26]
I'm not quite sure where to start debugging with this since I have a very strange setup but here it goes. I am trying to get terraria to work. I have it working on a livecd however on my actual system the game launches and I can move around in the menu with the keyboard but nothing else works. The largest difference is the fact I am on wayland on my main pc. However I don't see why this would be the issues considering the following. The keyboard works and the mouse works in other flatpaks. This is the only place I know to possibly see to find if you had an idea why this is happening?

**Comment by kujeger** [comment]
I just pushed a change that uses the newer 20.08 freedesktop runtime; could you try pulling the latest master and retry? I don't own terraria myself, so can't test.

**Comment by Muvkina** [comment]
Will do here now sorry for the long response time. @kujeger No such luck. I opened an issue on flatpak-runtime about possibility that sdl2 the mouse just doesn't work on wayland so I will update here when relevant.

**Comment by kujeger** [comment]
I pushed some more things now, including a change to how SDL2 is handled. It is possible that might have a positive effect on this issue.

I know mouse under SDL2 and wayland works fine for me with several games, so it is curious it does not with Terraria.

**Comment by Muvkina** [comment]
Could confirm this was a wayland issue beyond just flatpak. Terraria sdl just does not like wayland at all. So I will close this now. That said Terraria with the environment SDL_VIDEODRIVER=x11 works great with this tool.
