### ISSUE TITLE
flatpak-gog on Fedora Silverblue

### ISSUE THREAD

**Issue by dubst3pp4** [kujeger/flatpak-gog#28]
Just wanted to say a big THANK YOU as this project lets me build flatpaks for my purchased GOG games on Fedora Silverblue, where flatpaks are the preferred way to run graphical applications. It worked like a charme with [Encased Game](https://www.gog.com/de/game/encased_a_scifi_postapocalyptic_rpg), everything works out-of-the-box. I'm really happy :smile: 

Just a minor suggestion for the README:

the flatpak identifier for `GL32` is: 

```
flatpak --user install flathub org.freedesktop.Platform.GL32.default/x86_64/22.08
```

and not:

```
flatpak --user install flathub org.freedesktop.Platform.GL32/x86_64/22.08
```

And maybe you should mention (for non experienced users) that they should do a 

```
git submodule init && git submodule update --recursive
```

first, before they can use your script.

Best regards
Marc (who will now try to build all his other games, too)

**Comment by kujeger** [comment]
Hi, very happy you've found it useful, and thanks for reaching out! I'll update the README :)
