### ISSUE TITLE
Some minor issues I noticed (and an addition)

### ISSUE THREAD

**Issue by Pixelnarium** [kujeger/flatpak-gog#4]
At first, thanks for this project. I use a self made variant of this using just the freedesktop runtime since it works with everything I have. I noticed some smaller issues:

1. sed command in Template.json probably not what you want
You call sed -i='' and I think you want to prevent the command from making a backup? But with this command you will create a "Template.desktop=" backup file. Just remove the "=''" to make in-place updates without a backup. So just -i without any suffix.

2. --device=dri will just give you OpenGL but no controller input
For games it is more recommend to use --device=all to allow controllers to be used.

3. use shared-modules
Flathub offers a shared-modules repo for common flatpak addition. It's localed [here](https://github.com/flathub/shared-modules) and is supposed to be used as git submodule. You can just reference them in the modules path. An example for GLU is [here](https://github.com/flathub/net.sourceforge.chromium-bsu/blob/master/net.sourceforge.chromium-bsu.json)

4. is an own OpenAL installation really needed? I think it is already part of the runtime. But maybe the GNOME 3.24 runtime is too old (3.26 and 3.28 are a thing)

So, now an addition. Starbound wants to create a storage folder inside its game directory for saves. So create and link the folder at startup or else it will crash.

configure-Starbound
```
#!/bin/bash
cd /app/game/game/
ln -s /var/data/storage .
```

starter-Starbound
```
#!/bin/bash

if [ ! -d /var/data/storage ]
then
    mkdir /var/data/storage
fi

cd /app/game/
./start.sh
```

**Comment by kujeger** [comment]
Thanks!

I'll fix up points 1 and 2 ASAP, and look into 3 and 4 as well. I remember games crashing because of missing OpenAL back when I added it, but it's possible it is no longer needed.

**Comment by kujeger** [comment]
I pulled in the changes from your fork, so all of these are implemented now :-)

(really nice work in your fork btw)
