### ISSUE TITLE
Games starting with a number get an invalid app id

### ISSUE THREAD

**Issue by V02460** [kujeger/flatpak-gog#8]
Trying to create a flatpack from [7 Billion Humans](https://www.gog.com/game/7_billion_humans_pack) creates the invalid app id `com.gog.7BillionHumans` and flatpak-builder complains with

    error: 'com.gog.7BillionHumans' is not a valid application name: Name segment can't start with 7

**Comment by kujeger** [comment]
Perhaps automatically replacing e.g. '7' with 'Seven' at the start of the name would be nicest, rather than e.g. prefixing with underscore
com.gog.SevenBillionHumans
vs
com.gog._7BillionHumans

**Comment by kujeger** [comment]
A quick look at the gog store shows these games currently starting with a number:
140
2064: Read Only Memories
7 Billion Humans
88 Heroes

com.gog.Two064ReadOnlyMemories doesn't work quite as well, hmm.
